# Generated by Django 5.2.1 on 2025-05-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carpools", "0002_carpool_author_alter_carpool_seats_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpool",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
