# Generated by Django 5.2.1 on 2025-05-17 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carpools", "0003_carpool_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarpoolComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carpool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="carpools.carpool",
                    ),
                ),
            ],
        ),
    ]
