# Generated by Django 5.2.1 on 2025-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_email_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=30),
        ),
    ]
